alias ls='ls --color=auto'
alias colors='/home/iselda/.colors.sh'
alias woman='man'
alias hx='helix'
alias vi='nvim'
alias vim='nvim'
alias emacs='emacs -nw'
alias fortune='misfortune'
alias screenshot='maim -s | xclip -selection clipboard -t image/png'
alias ssh='kitty +kitten ssh'
alias oracle='ssh zellie@cyndquil.com -i /home/iselda/.ssh/ssh-key-2024-05-23.key'
