[colors.primary]
# background = "#2E3440"
# foreground = "#1A1C1E"
background = "#000000"
foreground = "#FFFFFF"

[colors.bright]
# black = "#4C566A"
black = "#000000"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
# black = "#3B4252"
black = "#000000"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[env]
TERM = "xterm-256color"

[font]
size = 7.0

[font.offset]
x = 1
y = 1

[scrolling]
history = 5000

[window]
dynamic_padding = false
# opacity = 0.85
opacity = 0.0
title = "Alacritty"

[window.padding]
x = 5
y = 5
